/**
 * 错误代码常量
 * 格式: MODULE.ACTION.ERROR_TYPE
 * 前端将根据这些代码显示对应语言的错误消息
 */

// 通用错误
export const ERROR_CODES = {
    // 系统通用
    COMMON: {
        UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
        FORBIDDEN: 'COMMON.FORBIDDEN',
        NOT_FOUND: 'COMMON.NOT_FOUND',
        INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',
        INVALID_TOKEN: 'COMMON.INVALID_TOKEN',
    },

    // 认证模块
    AUTH: {
        LOGIN: {
            INVALID_CREDENTIALS: 'AUTH.LOGIN.INVALID_CREDENTIALS',
        },
        TOKEN: {
            INVALID_TYPE: 'AUTH.TOKEN.INVALID_TYPE',
            USER_NOT_FOUND: 'AUTH.TOKEN.USER_NOT_FOUND',
            USER_DISABLED: 'AUTH.TOKEN.USER_DISABLED',
        },
        CONFIG: {
            JWT_SECRET_MISSING: 'AUTH.CONFIG.JWT_SECRET_MISSING',
        },
    },

    // 用户模块
    USER: {
        CREATE: {
            ALREADY_EXISTS: 'USER.CREATE.ALREADY_EXISTS',
        },
        COMMON: {
            NOT_FOUND: 'USER.COMMON.NOT_FOUND',
            ID_REQUIRED: 'USER.COMMON.ID_REQUIRED',
        },
        PASSWORD: {
            OLD_PASSWORD_INCORRECT: 'USER.PASSWORD.OLD_PASSWORD_INCORRECT',
            SAME_AS_OLD: 'USER.PASSWORD.SAME_AS_OLD',
        },
    },

    // 角色模块
    ROLE: {
        CREATE: {
            ALREADY_EXISTS: 'ROLE.CREATE.ALREADY_EXISTS',
        },
        COMMON: {
            NOT_FOUND: 'ROLE.COMMON.NOT_FOUND',
            ID_REQUIRED: 'ROLE.COMMON.ID_REQUIRED',
        },
    },

    // 权限模块
    PERMISSION: {
        CREATE: {
            CODE_ALREADY_EXISTS: 'PERMISSION.CREATE.CODE_ALREADY_EXISTS',
        },
        COMMON: {
            NOT_FOUND: 'PERMISSION.COMMON.NOT_FOUND',
            ID_REQUIRED: 'PERMISSION.COMMON.ID_REQUIRED',
        },
    },

    // 部门模块
    DEPARTMENT: {
        CREATE: {
            ALREADY_EXISTS: 'DEPARTMENT.CREATE.ALREADY_EXISTS',
            PARENT_NOT_FOUND: 'DEPARTMENT.CREATE.PARENT_NOT_FOUND',
        },
        UPDATE: {
            PARENT_NOT_FOUND: 'DEPARTMENT.UPDATE.PARENT_NOT_FOUND',
        },
        COMMON: {
            NOT_FOUND: 'DEPARTMENT.COMMON.NOT_FOUND',
            ID_REQUIRED: 'DEPARTMENT.COMMON.ID_REQUIRED',
        },
    },

    // 项目模块
    PROJECT: {
        CREATE: {
            CODE_ALREADY_EXISTS: 'PROJECT.CREATE.CODE_ALREADY_EXISTS',
            MANAGER_NOT_FOUND: 'PROJECT.CREATE.MANAGER_NOT_FOUND',
        },
        UPDATE: {
            MANAGER_NOT_FOUND: 'PROJECT.UPDATE.MANAGER_NOT_FOUND',
        },
        MEMBER: {
            ALREADY_EXISTS: 'PROJECT.MEMBER.ALREADY_EXISTS',
            USER_NOT_FOUND: 'PROJECT.MEMBER.USER_NOT_FOUND',
        },
        COMMON: {
            NOT_FOUND: 'PROJECT.COMMON.NOT_FOUND',
            ID_REQUIRED: 'PROJECT.COMMON.ID_REQUIRED',
        },
    },

    // 报表配置模块
    REPORT_CONFIG: {
        CREATE: {
            TYPE_ALREADY_EXISTS: 'REPORT_CONFIG.CREATE.TYPE_ALREADY_EXISTS',
        },
        UPDATE: {
            NOT_FOUND: 'REPORT_CONFIG.UPDATE.NOT_FOUND',
        },
        DELETE: {
            NOT_FOUND: 'REPORT_CONFIG.DELETE.NOT_FOUND',
        },
        COMMON: {
            NOT_FOUND: 'REPORT_CONFIG.COMMON.NOT_FOUND',
            ID_REQUIRED: 'REPORT_CONFIG.COMMON.ID_REQUIRED',
        },
    },

    // 工时模块
    TIMESHEET: {
        CREATE: {
            PROJECT_NOT_FOUND: 'TIMESHEET.CREATE.PROJECT_NOT_FOUND',
            PROJECT_NOT_IN_PROGRESS: 'TIMESHEET.CREATE.PROJECT_NOT_IN_PROGRESS',
            NOT_PROJECT_MEMBER: 'TIMESHEET.CREATE.NOT_PROJECT_MEMBER',
            FUTURE_DATE_NOT_ALLOWED: 'TIMESHEET.CREATE.FUTURE_DATE_NOT_ALLOWED',
            DUPLICATE_RECORD: 'TIMESHEET.CREATE.DUPLICATE_RECORD',
        },
        SUBMIT: {
            NOT_OWNER: 'TIMESHEET.SUBMIT.NOT_OWNER',
            INVALID_STATUS: 'TIMESHEET.SUBMIT.INVALID_STATUS',
        },
        REVIEW: {
            INVALID_STATUS: 'TIMESHEET.REVIEW.INVALID_STATUS',
            NO_PERMISSION: 'TIMESHEET.REVIEW.NO_PERMISSION',
        },
        UPDATE: {
            NOT_OWNER: 'TIMESHEET.UPDATE.NOT_OWNER',
            INVALID_STATUS: 'TIMESHEET.UPDATE.INVALID_STATUS',
            PROJECT_NOT_FOUND: 'TIMESHEET.UPDATE.PROJECT_NOT_FOUND',
            PROJECT_NOT_IN_PROGRESS: 'TIMESHEET.UPDATE.PROJECT_NOT_IN_PROGRESS',
            NOT_PROJECT_MEMBER: 'TIMESHEET.UPDATE.NOT_PROJECT_MEMBER',
            FUTURE_DATE_NOT_ALLOWED: 'TIMESHEET.UPDATE.FUTURE_DATE_NOT_ALLOWED',
        },
        DELETE: {
            NOT_OWNER: 'TIMESHEET.DELETE.NOT_OWNER',
            INVALID_STATUS: 'TIMESHEET.DELETE.INVALID_STATUS',
        },
        RECALL: {
            NOT_OWNER: 'TIMESHEET.RECALL.NOT_OWNER',
            INVALID_STATUS: 'TIMESHEET.RECALL.INVALID_STATUS',
        },
        COMMON: {
            NOT_FOUND: 'TIMESHEET.COMMON.NOT_FOUND',
        },
    },

    // WebSocket模块
    WEBSOCKET: {
        AUTH: {
            NO_TOKEN: 'WEBSOCKET.AUTH.NO_TOKEN',
            INVALID_TOKEN: 'WEBSOCKET.AUTH.INVALID_TOKEN',
        },
        CONNECTION: {
            FAILED: 'WEBSOCKET.CONNECTION.FAILED',
        },
    },
} as const;

// 导出类型以便TypeScript类型检查
export type ErrorCode = string;
