/**
 * 成功代码常量
 * 格式: MODULE.ACTION.SUCCESS
 * 前端将根据这些代码显示对应语言的成功消息
 */

export const SUCCESS_CODES = {
    // 通用成功
    COMMON: {
        SUCCESS: 'COMMON.SUCCESS',
    },

    // 认证模块
    AUTH: {
        LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
        REGISTER_SUCCESS: 'AUTH.REGISTER.SUCCESS',
        REFRESH_TOKEN_SUCCESS: 'AUTH.REFRESH_TOKEN.SUCCESS',
        GET_USER_INFO_SUCCESS: 'AUTH.GET_USER_INFO.SUCCESS',
    },

    // 用户模块
    USER: {
        RESET_PASSWORD_SUCCESS: 'USER.RESET_PASSWORD.SUCCESS',
        CHANGE_PASSWORD_SUCCESS: 'USER.CHANGE_PASSWORD.SUCCESS',
    },

    // 工时模块
    TIMESHEET: {
        CREATE_SUCCESS: 'TIMESHEET.CREATE.SUCCESS',
        BATCH_CREATE_SUCCESS: 'TIMESHEET.BATCH_CREATE.SUCCESS',
        UPDATE_SUCCESS: 'TIMESHEET.UPDATE.SUCCESS',
        DELETE_SUCCESS: 'TIMESHEET.DELETE.SUCCESS',
        SUBMIT_SUCCESS: 'TIMESHEET.SUBMIT.SUCCESS',
        BATCH_SUBMIT_SUCCESS: 'TIMESHEET.BATCH_SUBMIT.SUCCESS',
        WITHDRAW_SUCCESS: 'TIMESHEET.WITHDRAW.SUCCESS',
        REVIEW_SUCCESS: 'TIMESHEET.REVIEW.SUCCESS',
        BATCH_REVIEW_SUCCESS: 'TIMESHEET.BATCH_REVIEW.SUCCESS',
    },
} as const;

// 导出类型以便TypeScript类型检查
export type SuccessCode = string;
