/**
 * 验证消息代码常量
 * 格式: VALIDATION.MODULE.FIELD.ERROR_TYPE
 * 前端将根据这些代码显示对应语言的验证错误消息
 */

export const VALIDATION_CODES = {
    // 通用验证
    COMMON: {
        REQUIRED: 'VALIDATION.COMMON.REQUIRED',
        INVALID_FORMAT: 'VALIDATION.COMMON.INVALID_FORMAT',
        MUST_BE_STRING: 'VALIDATION.COMMON.MUST_BE_STRING',
        MUST_BE_NUMBER: 'VALIDATION.COMMON.MUST_BE_NUMBER',
    },

    // 密码验证
    PASSWORD: {
        OLD_PASSWORD_REQUIRED: 'VALIDATION.PASSWORD.OLD_PASSWORD_REQUIRED',
        NEW_PASSWORD_REQUIRED: 'VALIDATION.PASSWORD.NEW_PASSWORD_REQUIRED',
        CONFIRM_PASSWORD_REQUIRED: 'VALIDATION.PASSWORD.CONFIRM_PASSWORD_REQUIRED',
        MIN_LENGTH: 'VALIDATION.PASSWORD.MIN_LENGTH',
    },

    // 工时验证
    TIMESHEET: {
        PROJECT_CODE_REQUIRED: 'VALIDATION.TIMESHEET.PROJECT_CODE_REQUIRED',
        WORK_DATE_REQUIRED: 'VALIDATION.TIMESHEET.WORK_DATE_REQUIRED',
        WORK_DATE_INVALID: 'VALIDATION.TIMESHEET.WORK_DATE_INVALID',
        HOURS_REQUIRED: 'VALIDATION.TIMESHEET.HOURS_REQUIRED',
        HOURS_MUST_BE_NUMBER: 'VALIDATION.TIMESHEET.HOURS_MUST_BE_NUMBER',
        HOURS_MIN: 'VALIDATION.TIMESHEET.HOURS_MIN',
        HOURS_MAX: 'VALIDATION.TIMESHEET.HOURS_MAX',
        RECORDS_REQUIRED: 'VALIDATION.TIMESHEET.RECORDS_REQUIRED',
        RECORDS_MUST_BE_ARRAY: 'VALIDATION.TIMESHEET.RECORDS_MUST_BE_ARRAY',
        RECORDS_MIN_SIZE: 'VALIDATION.TIMESHEET.RECORDS_MIN_SIZE',
        RECORDS_MAX_SIZE: 'VALIDATION.TIMESHEET.RECORDS_MAX_SIZE',
    },
} as const;

// 导出类型以便TypeScript类型检查
export type ValidationCode = string;
